import Head from "next/head";
import Header from "../include/header";
import Footer from "../include/footer";


function ContactUs(props){

    return (
        <div className={`app`}>
            <Head>
                <title>ارتباط ما | بانی ارز دیجیتال</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header />

            <main className={``}>
                ContactUs
            </main>

            <Footer />
        </div>
    );
}

export default ContactUs;