import Head from "next/head";
import Header from "../include/header";
import Footer from "../include/footer";
import {useState} from "react";
import Input from "../component/forms/input";
import Textarea from "../component/forms/textarea";
import HeadInclude from '../include/headInclude';
import {MdMap, MdSettingsPhone, MdMarkEmailUnread} from "react-icons/md";

function ContactUs(props) {
    const [form, setForm] = useState({
        'full_name': "",
        'mobile': "",
        'email': "",
        'subject': "",
        'content': "",
    });

    const [message, setMessage] = useState({
        "message": ""
    })


    const SetData = (event) => {
        console.log(event.target.name, event.target.value)
        setForm({
            ...form,
            [event.target.name]: event.target.value,
        })
    }


    return (
        <div className={`app`}
             dir={`rtl`}>
            <Head>
                <HeadInclude/>
                <title>ارتباط ما | بانی ارز دیجیتال</title>
                <meta name="description"
                      content="Generated by create next app"/>
                <link rel="icon"
                      href="/favicon.ico"/>
            </Head>

            <Header/>

            <main className={`container bg-white shadow-sm p-4 border-radius-theme my-4`}>

                <div className="row">
                    <div className="col-md-6">
                        <div className="">
                            <h1 className="font-20 mb-4">
                                ارتباط با ما
                            </h1>
                            <div className="row">
                                <div className="col-sm-12">
                                    <div className="contact-item">
                                        <p className="mb-2 text-secondary font-15 fw-bold">
                                            <MdMap  className={`font-18`}/>
                                            آدرس
                                        </p>
                                        <p className="px-4 text-secondary font-14">
                                            قزوین مرکز رشد دانشگاه آزاد قزوین
                                        </p>
                                    </div>
                                </div>
                                <div className="col-sm-6">
                                    <div className="contact-item">
                                        <p className="mb-2 text-secondary font-15 fw-bold">
                                            <MdSettingsPhone  className={`font-18`}/>
                                            تلفن:
                                        </p>
                                        <p className="px-4 text-secondary font-14">
                                            <a href="call:+982833681600"
                                               className="text-decoration-none "
                                               dir="ltr">
                                                028-33681600
                                            </a>
                                        </p>
                                    </div>
                                </div>
                                <div className="col-sm-6">
                                    <div className="contact-item">
                                        <p className="mb-2 text-secondary font-15 fw-bold">
                                            <MdMarkEmailUnread  className={`font-18`}/>
                                            ایمیل:
                                        </p>
                                        <p className="px-4 text-secondary font-14">
                                            <a href="mailTo:info@baniarzdigital.com"
                                               className="text-decoration-none "
                                               dir="ltr">
                                                info [at] baniarzdigital.com
                                            </a>
                                        </p>
                                    </div>
                                </div>
                                <div className="col-sm-12">
                                    <div className="contact-item">
                                        <p className="mb-2 text-secondary font-15 fw-bold">
                                            <i className="icon map pin"></i>
                                            موقعیت:
                                        </p>

                                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3941.886703143032!2d50.03863225987374!3d36.32257131863689!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xdbabf03ed1f825d!2zMzbCsDE5JzIxLjEiTiA1MMKwMDInMjEuNiJF!5e1!3m2!1sen!2s!4v1646140615996!5m2!1sen!2s"
                                                width="100%"
                                                height="350"
                                                allowFullScreen=""
                                                loading="lazy"></iframe>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-md-6">
                        <div className="px-2">
                            <p className="text-start text-secondary font-15  mb-4">
                                برای ارسال پیام (نظر - پیشنهاد - سوال و ...) لطفا فرم زیر را پر کنید
                            </p>

                            {
                                message.message !== ""
                                    ? (
                                        <div className="alert d-block alert-success w-100">
                                            <p className="m-0">{ message.message }</p>
                                        </div>
                                    )
                                    : null
                            }


                            <form action="/"
                                  method="post">
                                <input type="hidden"
                                       name="method"
                                       value="POST"
                                       id="method"/>
                                <div className="row">
                                    <div className="col-sm-12">
                                        <Input label={"نام و نام خانوادگی"}
                                               name={"full_name"}
                                               onChange={SetData}
                                               value={form.full_name}
                                               required={true}/>
                                    </div>
                                    <div className="col-sm-6">
                                        <Input label={"شماره موبایل"}
                                               name={"mobile"}
                                               type="mobile"
                                               value={form.mobile}
                                               onChange={SetData}
                                               required={true}/>
                                    </div>
                                    <div className="col-sm-6">
                                        <Input label={"آدرس ایمیل"}
                                               name={"email"}
                                               type="email"
                                               value={form.email}
                                               onChange={SetData}
                                               required={true}/>
                                    </div>
                                    <div className="col-sm-12">
                                        <Input label={"موضوع"}
                                               name={"subject"}
                                               type="text"
                                               value={form.subject}
                                               onChange={SetData}
                                               required={true}/>
                                    </div>
                                    <div className="col-sm-12">
                                        <Textarea label={"متن درخواست"}
                                                  name="content"
                                                  onChange={SetData}
                                                  required={true}
                                                  value={form.mobile}
                                                  rows="6"/>
                                    </div>
                                </div>
                                <div className="row my-4">
                                    <div className="col-sm-12 d-flex justify-content-between">
                                        <button type="submit"
                                                className="btn btn-success px-5">
                                            ارسال
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </main>

            <Footer/>
        </div>
    );
}

export default ContactUs;