import Head from "next/head";
import HeadInclude from "../include/headInclude";
import Header from "../include/header";
import HomeSlider from "../component/home/slider/homeSlider";
import Link from "next/link";
import PostSwiperSlider from "../component/home/swiper/postSwiperSlider";
import {BsBookmarks} from "react-icons/bs";
import SuggestionMostView from "../component/home/suggestionMostView/suggestionMostView";
import FooterAboutUs from "../include/footerAboutUs";
import Footer from "../include/footer";

function Posts (props){
    return (
        <div className={`app`}
             dir={`rtl`}>
            <Head>
                <HeadInclude/>
                <title>صفحه اصلی | بانی ارز دیجیتال</title>
                <meta name="description"
                      content="Generated by create next app"/>

            </Head>

            <Header/>

            <main className={`main`}>


                <FooterAboutUs />
            </main>

            <Footer/>
        </div>
    );
}

export default Posts;