import Head from 'next/head'
import Image from 'next/image'
import Footer from './include/footer';
import Header from './include/header';

function Home(props) {
    return (
        <div className={`app`}>
            <Head>
                <title>صفحه اصلی | بانی ارز دیجیتال</title>
                <meta name="description"
                      content="Generated by create next app"/>
                <link rel="icon"
                      href="/favicon.ico"/>
            </Head>

            <Header />

            <main className={``}>
aa
            </main>

            <Footer />
        </div>
    )
}

export default Home;